### ISSUE TITLE
решение квадратных уранений

### ISSUE THREAD

**Issue by AlinaMedik** [AlinaMedik/2#1]
Выполнила Сладкомедова Алина

Tо: @evgeny-p

**Comment by evgeny-p** [comment]
Замечания по коду:
1. Как дискриминант может быть одновременно и больше нуля и равен ему?
   
   ``` c
   if ((d > 0) && (d == 0))
   ```
2. Код не отформатирован. Отступы не соответствуют структуре кода. Для отступов используется смесь табов и пробелов. Бинарный оператор в строке 15 не выделен пробелами.

На будущее: история изменений нерепрезентативная. Вот так сейчас выглядит лог:

```
*   6405ebc (HEAD, origin/master, origin/HEAD, master) Merge branch 'feature'
|\  
| * 050f695 конечная функция
| * 16d6a14 вносим изменения в коммит
| * 9a0498e вносим изменения в коммит
| * 54f19a4 вносим изменения в коммит
| * 2ebd619 вносим изменения в коммит
| * 39d27a8 вносим изменения в коммит
|/  
* d72eb57 вносим изменения  в коммит
```

Сообщения никак не характеризуют содержание коммитов.

**Comment by AlinaMedik** [comment]
исправлено

**Comment by evgeny-p** [comment]
Принято.
